# -*- coding: utf-8 -*-
"""
# Agente de Saúde Mental e Bem-Estar - Sistema Multi-Agente Finalizado com Mentor

Este código Python implementa um sistema de agentes conversacionais para auxiliar
pessoas com problemas emocionais e promover exercícios, seguindo um padrão
inspirado no Agent Development Kit (ADK) do Google. Ele separa as responsabilidades
em múltiplos Agentes especializados, incluindo um novo Agente Mentor, Ferramentas
(Tools) e um Orquestrador.

## Configuração no Google Colab

Para executar este código no Google Colab, siga os passos abaixo:

1.  **Instalar a biblioteca google-generativeai:**
    Execute a seguinte linha em uma célula do seu notebook Colab:
    ```bash
    !pip install google-generativeai
    ```

2.  **Obter sua Chave de API do Google AI Studio:**
    Se você ainda não tem uma chave de API, acesse o Google AI Studio
    (https://aistudio.google.com/) e crie uma nova chave de API.

3.  **Configurar a Chave de API no Colab (Recomendado: Secrets Manager):**
    A forma mais segura de configurar sua chave de API no Google Colab é usando o
    Secrets Manager:
    * No menu à esquerda do Colab, clique no ícone de chave (`🔑`).
    * Clique em `Gerenciar secrets`.
    * Clique em `+ Novo secret`.
    * No campo `Nome`, inscreva um nome para o seu secret (por exemplo, `GOOGLE_API_KEY`).
    * No campo `Valor`, cole o valor da sua chave de API real.
    * Certifique-se de que a opção `Notebook access` está ativada para este secret.
    * No código abaixo, descomente as linhas que carregam a chave usando `userdata.get()`
        e comente a linha `API_KEY = "YOUR_API_KEY"`.
    * Substitua `'YOUR_API_KEY_NAME_IN_SECRETS'` pelo nome que você deu ao seu secret
        no Secrets Manager.

    Alternativamente (NÃO RECOMENDADO para chaves sensíveis), você pode substituir
    a string placeholder `"YOUR_API_KEY"` diretamente no código pela sua chave real,
    mas **tenha cuidado para não compartilhar seu notebook com a chave exposta**.

4.  **Executar o Código:**
    Execute as células do código no seu notebook Colab. A função `main()` iniciará
    o sistema de agentes e você poderá interagir com ele através da linha de comando
    no output da célula.

## Estrutura do Código

O código está organizado da seguinte forma:

-   **Ferramentas (Tools):** Classes que encapsulam interações com serviços externos,
    como a `GeminiTool` para comunicação com o modelo Gemini.
-   **Agentes (Agents):** Classes que herdam de `BaseAgent` e implementam a lógica
    especializada para diferentes domínulos (Suporte Emocional, Exercício, Conhecimento, Mentor).
-   **Orquestrador (Orchestrator):** Gerencia o fluxo da conversa, roteia as entradas
    do usuário para os agentes apropriados e mantém o estado (histórico da conversa,
    perfil do usuário).
-   **main():** Função principal que configura o ambiente (API, ferramentas, agentes)
    e inicia o Orquestrador.

"""

import os
import datetime
import random # Importação da biblioteca random adicionada
from typing import List, Dict, Any, Optional
# IMPORTANTE: A biblioteca google-generativeai precisa ser instalada no ambiente
# Para Google Colab, execute: !pip install google-generativeai
import google.generativeai as genai

# --- Definição das Ferramentas (Tools) ---
# A classe GeminiTool foi movida para cá para ser definida antes de ser usada.

class GeminiTool:
    """
    Uma ferramenta para interagir com o modelo Gemini do Google AI Studio.
    Encapsula a lógica de chamada da API.
    """
    def __init__(self, model: genai.GenerativeModel):
        self.model = model

    def generate_text(self, prompt: str) -> str:
        """
        Generates text using the Gemini model.

        Args:
            prompt (str): The text prompt for the model.

        Returns:
            str: The text generated by the model.
        """
        try:
            # Configurações de segurança para garantir respostas apropriadas
            safety_settings = [
                {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
                {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
                {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
                {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
            ]
            # Geração de conteúdo com configurações de segurança
            response = self.model.generate_content(prompt, safety_settings=safety_settings)

            # Verifica se houve bloqueios de segurança
            if hasattr(response, 'prompt_feedback') and response.prompt_feedback.block_reason:
                 print(f"Conteúdo bloqueado por motivo de segurança: {response.prompt_feedback.block_reason}")
                 return "Desculpe, não posso responder a isso de acordo com minhas diretrizes de segurança."
            if hasattr(response, 'candidates') and not response.candidates:
                 print("Resposta bloqueada - nenhum candidato gerado.")
                 return "Desculpe, não consigo gerar uma resposta para isso no momento."


            return response.text.strip()
        except Exception as e:
            print(f"Erro na ferramenta Gemini ao gerar texto: {e}")
            return "Desculpe, não consigo processar sua solicitação no momento."


# --- Configuração da API do Google AI Studio ---
# É ALTAMENTE recomendado usar variáveis de ambiente ou o Secrets Manager do Colab
# para armazenar sua chave de API de forma segura.
# Exemplo usando variável de ambiente: os.getenv("GOOGLE_API_KEY")
# Substitua a string placeholder "YOUR_API_KEY" pela sua chave de API real.
API_KEY = "AIzaSyBqkjOJk6RVjZ_3ltr1Nbf19acdcGJZa_c" # SUA CHAVE DE API REAL

# --- Carregar chave usando Secrets Manager do Colab (descomente e configure o Secret) ---
# try:
#     from google.colab import userdata
#     API_KEY = userdata.get('YOUR_API_KEY_NAME_IN_SECRETS') # Substitua pelo nome do seu Secret
#     if API_KEY is None:
#         print("AVISO: Chave de API não encontrada no Secrets Manager.")
#         print("Por favor, configure seu Secret ou substitua 'YOUR_API_KEY' no código.")
# except ImportError:
#     print("AVISO: Não está no ambiente Google Colab ou a biblioteca userdata não está disponível.")
#     print("Por favor, substitua 'YOUR_API_KEY' no código pela sua chave de API real.")


# Variável global para a ferramenta Gemini (inicializada após configuração)
gemini_tool: Optional['GeminiTool'] = None
llm_model: Optional[genai.GenerativeModel] = None # Variável para o modelo LLM

if API_KEY == "YOUR_API_KEY":
    print("AVISO: A chave de API não foi configurada.")
    print("Por favor, substitua 'YOUR_API_KEY' no código pela sua chave de API real do Google AI Studio.")
    print("O sistema de agentes não poderá funcionar corretamente sem uma chave de API válida.")
else:
    try:
        genai.configure(api_key=API_KEY)
        # Use um modelo adequado para conversação. Verifique a documentação do Google AI Studio
        # ou use genai.list_models() para ver os modelos disponíveis e seus supported_methods.
        # 'gemini-1.5-flash-latest' é uma opção recente e geralmente disponível.
        llm_model = genai.GenerativeModel('gemini-1.5-flash-latest') # Modelo atualizado para gemini-1.5-flash-latest
        gemini_tool = GeminiTool(llm_model) # Inicializa a ferramenta Gemini
        # Pequeno teste para verificar a conexão - descomente se necessário para depuração
        # try:
        #     gemini_tool.generate_text("Test connection")
        #     print("Conexão com o Google AI Studio bem-sucedida.")
        # except Exception as test_e:
        #     print(f"ERRO: Falha no teste de conexão com o Google AI Studio: {test_e}")
        #     gemini_tool = None # Define a ferramenta como None em caso de falha no teste
    except Exception as e:
        print(f"ERRO: Falha ao configurar ou conectar ao Google AI Studio: {e}")
        print("Por favor, verifique sua chave de API e a configuração do modelo.")
        gemini_tool = None # Garante que a ferramenta seja None em caso de falha


# --- Definição dos Agentes ---

class BaseAgent:
    """Classe base para todos os agentes."""
    def __init__(self, name: str, version: str, gemini_tool: Optional[GeminiTool]):
        self.name = name
        self.version = version
        self.gemini_tool = gemini_tool

    def process_input(self, user_input: str, conversation_history: List[Dict[str, str]], user_profile: Dict[str, Any]) -> str:
        """
        Processa a entrada do usuário e gera uma resposta.
        Deve ser implementado pelas classes filhas.

        Args:
            user_input (str): A mensagem do usuário.
            conversation_history (List[Dict[str, str]]): Histórico completo da conversa.
            user_profile (Dict[str, Any]): Perfil do usuário.

        Returns:
            str: A resposta gerada pelo agente.
        """
        raise NotImplementedError("O método process_input deve ser implementado pelas subclasses.")

    def _build_prompt(self, user_input: str, conversation_history: List[Dict[str, str]], user_profile: Dict[str, Any], agent_instructions: str) -> str:
        """Constrói o prompt completo para o modelo Gemini."""
        context = f"{agent_instructions}\n\n"
        if user_profile:
            context += f"Perfil do Usuário: {user_profile}\n\n"
        context += "Histórico da Conversa:\n"
        # Inclui apenas uma parte relevante do histórico para evitar exceder o limite de tokens
        # A lógica de resumo ou seleção inteligente de histórico pode ser adicionada aqui.
        recent_history = conversation_history[-20:] # Exemplo: últimas 20 interações
        for message in recent_history:
            context += f"{message['sender']}: {message['content']}\n"
        context += f"\nUsuário: {user_input}\nAgente:"
        return context


class EmotionalSupportAgent(BaseAgent):
    """Agente especializado em suporte emocional (ansiedade, depressão, raiva, pensamentos intrusivos)."""
    def __init__(self, gemini_tool: Optional[GeminiTool]):
        super().__init__("AgenteSuporteEmocional", "1.0.13", gemini_tool) # Versão atualizada
        self.instructions = """
Você é o AgenteSuporteEmocional do BemEstarBot. Seu foco é fornecer suporte
empático e baseado em evidências para usuários que lidam com ansiedade,
depressão, raiva e pensamentos intrusivos. Utilize princípios de TCC e ACT de
forma conversacional.

Seja extremamente empático, ouvinte ativo e demonstre compreensão. Incentive o
usuário a compartilhar seus sentimentos e explore as situações com perguntas
abertas. Ofereça técnicas práticas e baseadas em estudos para gerenciar emoções
difíceis, sempre com um tom de apoio e sem julgamento.

Lembre-se de que você é uma IA e não um terapeuta. Em situações de sofrimento
significativo ou crise, reforce a importância de procurar ajuda profissional.

Considere o histórico da conversa para manter o contexto e personalize suas
respostas com base no que o usuário já compartilhou.
"""

    def process_input(self, user_input: str, conversation_history: List[Dict[str, str]], user_profile: Dict[str, Any]) -> str:
        if not self.gemini_tool:
            return "Desculpe, o Agente de Suporte Emocional não está disponível no momento."

        prompt = self._build_prompt(user_input, conversation_history, user_profile, self.instructions)
        return self.gemini_tool.generate_text(prompt)


class ExerciseAgent(BaseAgent):
    """Agente especializado em promover e recomendar exercícios físicos."""
    def __init__(self, gemini_tool: Optional[GeminiTool]):
        super().__init__("AgenteExercicio", "1.0.13", gemini_tool) # Versão atualizada
        self.instructions = """
Você é o AgenteExercicio do BemEstarBot. Seu foco é motivar e guiar os usuários
na prática de exercícios físicos para melhorar seu bem-estar físico e mental.
Suas recomendações devem ser baseadas em evidências científicas e diretrizes de
saúde (OMS, AHA, etc.).

Seja encorajador, positivo e prático. Pergunte sobre os hábitos atuais,
preferências e barreiras do usuário para oferecer sugestões personalizadas.
Explique os benefícios científicos do exercício para a saúde mental (redução de
ansiedade/depressão, melhora do humor).

Sugira começar pequeno e aumentar gradualmente. Ofereça diferentes tipos de
exercício (caminhada, corrida, força, yoga) com base nas preferências e
evidências.

Considere o histórico da conversa para lembrar de objetivos ou progressos
anteriores e personalize suas mensagens motivacionais.
"""

    def process_input(self, user_input: str, conversation_history: List[Dict[str, str]], user_profile: Dict[str, Any]) -> str:
        if not self.gemini_tool:
            return "Desculpe, o Agente de Exercício não está disponível no momento."

        prompt = self._build_prompt(user_input, conversation_history, user_profile, self.instructions)
        return self.gemini_tool.generate_text(prompt)

class KnowledgeAgent(BaseAgent): # Corrigido: Herdar de BaseAgent
    """Agente especializado em fornecer informações baseadas em estudos e artigos científicos."""
    def __init__(self, gemini_tool: Optional[GeminiTool]):
        super().__init__("AgenteConhecimento", "1.0.13", gemini_tool) # Versão atualizada
        self.instructions = """
Você é o AgenteConhecimento do BemEstarBot. Seu foco é fornecer informações
precisas e baseadas em estudos e artigos científicos sobre saúde mental,
bem-estar e os benefícios do exercício.

Responda às perguntas do usuário com informações claras, concisas e, quando
possível, referencie (de forma conversacional) que a informação é baseada em
evidências. Evite dar conselhos médicos diretos.

Seja informativo e objetivo. Se uma pergunta estiver fora do seu escopo de
conhecimento científico (por exemplo, "Como faço para cozinhar macarrão?"),
indique que você se concentra em saúde e bem-estar baseados em evidências.

Considere o histórico da conversa para entender o contexto da pergunta por
informação.
"""

    def process_input(self, user_input: str, conversation_history: List[Dict[str, str]], user_profile: Dict[str, Any]) -> str:
        if not self.gemini_tool:
            return "Desculpe, o Agente de Conhecimento não está disponível no momento."

        prompt = self._build_prompt(user_input, conversation_history, user_profile, self.instructions)
        return self.gemini_tool.generate_text(prompt)

class MentorAgent(BaseAgent):
    """Agente especializado em atuar como mentor, motivador e acompanhador recorrente."""
    def __init__(self, gemini_tool: Optional[GeminiTool]):
        super().__init__("AgenteMentor", "1.0.10", gemini_tool) # Versão atualizada
        self.instructions = """
Você é o AgenteMentor do BemEstarBot. Seu papel é ser um mentor, guia e motivador
constante para o usuário em sua jornada de saúde mental e bem-estar. Sua
comunicação deve ser inspiradora, empática e focada no progresso a longo prazo.
Pense em um estilo de comunicação que combine sabedoria, encorajamento e um toque
pessoal, como um mentor experiente.

Seja proativo no acompanhamento. Lembre o usuário de seus objetivos, celebre
pequenas vitórias e ofereça suporte em momentos de dificuldade. Utilize o histórico
da conversa e o perfil do usuário (se disponível) para personalizar suas mensagens
e demonstrar que você se lembra do progresso e dos desafios anteriores.

Incentive a consistência nos exercícios e na aplicação das técnicas de saúde mental.
Faça perguntas que levem à reflexão sobre o progresso e os aprendizados.

Sua recorrência é chave: em uma implementação completa, você iniciaria conversas
periodicamente para fazer check-ins e oferecer suporte contínuo. Nesta simulação,
você responderá quando o usuário abordar tópicos relacionados a progresso,
motivação, objetivos ou acompanhamento.

Mantenha um tom caloroso, paciente e inspirador.
"""

    def process_input(self, user_input: str, conversation_history: List[Dict[str, str]], user_profile: Dict[str, Any]) -> str:
        if not self.gemini_tool:
            return "Desculpe, o Agente Mentor não está disponível no momento."

        prompt = self._build_prompt(user_input, conversation_history, user_profile, self.instructions)
        return self.gemini_tool.generate_text(prompt)


# --- Orquestrador ---

class Orchestrator:
    """
    Orquestrador que gerencia os agentes, ferramentas e o fluxo da conversa.
    Responsável por rotear as entradas do usuário para o agente apropriado.
    """
    def __init__(self, agents: Dict[str, BaseAgent]):
        self.agents = agents
        self.conversation_history: List[Dict[str, str]] = []
        self.user_profile: Dict[str, Any] = {} # Futuramente para armazenar dados do usuário
        self.version = "1.0.13" # Versão do Orquestrador atualizada

    def _log_conversation(self, sender: str, message: str) -> None:
        """
        Adiciona uma mensagem ao histórico da conversa.
        """
        # Limitar o tamanho do histórico para não exceder o limite de tokens do modelo
        if len(self.conversation_history) > 100: # Aumentado o limite para múltiplos agentes
             self.conversation_history = self.conversation_history[-100:]

        self.conversation_history.append({"sender": sender, "content": message})

    def route_input_to_agent(self, user_input: str) -> str:
        """
        Direciona a entrada do usuário para o agente apropriado com base em palavras-chave simples.
        Em uma implementação real, isso usaria PLN mais avançado.

        Args:
            user_input (str): A mensagem do usuário.

        Returns:
            str: O nome do agente selecionado para processar a entrada.
        """
        user_input_lower = user_input.lower()

        # Lógica de roteamento simples baseada em palavras-chave
        # Adicionando palavras-chave para o Agente Mentor
        if any(keyword in user_input_lower for keyword in ["mentor", "acompanhar", "motivar", "progresso", "objetivo", "meta", "como estou indo", "seguir em frente"]):
            agent_name = "AgenteMentor"
        elif any(keyword in user_input_lower for keyword in ["ansiedade", "depressão", "triste", "raiva", "pensamentos ruins", "sentindo", "emocional", "lidar com"]):
            agent_name = "AgenteSuporteEmocional"
        elif any(keyword in user_input_lower for keyword in ["exercício", "atividade física", "academia", "caminhada", "corrida", "malhar", "treino", "movimento", "ativo"]):
            agent_name = "AgenteExercicio"
        elif any(keyword in user_input_lower for keyword in ["estudo", "pesquisa", "científico", "benefícios", "informação", "evidência", "saber sobre", "o que é"]):
             agent_name = "AgenteConhecimento"
        else:
            # Se nenhuma palavra-chave específica for encontrada, direciona para o agente emocional como padrão
            # ou poderia ter um agente "Geral" ou "Saudação".
            agent_name = "AgenteSuporteEmocional" # Padrão para conversas gerais/emocionais

        return agent_name


    def process_user_input(self, user_input: str) -> str:
        """
        Recebe a entrada do usuário, roteia para o agente apropriado e retorna a resposta.

        Args:
            user_input (str): A mensagem do usuário.

        Returns:
            str: A resposta gerada pelo agente selecionado.
        """
        self._log_conversation("user", user_input) # Log antes de rotear

        # Roteia a entrada para o agente apropriado
        agent_name = self.route_input_to_agent(user_input)
        agent = self.agents.get(agent_name)

        if agent:
            print(f"(Orquestrador: Roteando para {agent.name})") # Para visualização no console
            # Chama o método process_input do agente selecionado
            response = agent.process_input(user_input, self.conversation_history, self.user_profile)
        else:
            response = "Desculpe, não consigo encontrar um agente adequado para lidar com isso."

        self._log_conversation("bot", response) # Log da resposta do bot
        return response


    def run(self) -> None:
        """Executa o loop principal do orquestrador."""
        # Verifica se a ferramenta Gemini foi inicializada com sucesso globalmente
        # Esta verificação foi movida para main() para melhor organização
        # pass # Removemos a verificação duplicada aqui


        print(f"\nOrquestrador (versão {self.version}) iniciado.")

        # Saudação inicial (tratada pelo orquestrador chamando um agente)
        # Pode ser o Agente Mentor ou Emocional para iniciar de forma acolhedora
        initial_greeting_agent = self.agents.get("AgenteMentor") # Usando o Mentor para a saudação inicial
        if initial_greeting_agent:
             initial_greeting = initial_greeting_agent.process_input("Início da conversa.", self.conversation_history, self.user_profile)
             self._log_conversation("bot", initial_greeting)
             print(f"BemEstarBot: {initial_greeting}")
        else:
             # Fallback caso o Agente Mentor não esteja disponível
             fallback_greeting_agent = self.agents.get("AgenteSuporteEmocional")
             if fallback_greeting_agent:
                  initial_greeting = fallback_greeting_agent.process_input("Início da conversa.", self.conversation_history, self.user_profile)
                  self._log_conversation("bot", initial_greeting)
                  print(f"BemEstarBot: {initial_greeting}")
             else:
                  print("BemEstarBot: Olá! Sou o BemEstarBot. No momento, estou com dificuldades para iniciar. Como posso te ajudar?")


        while True:
            user_input: str = input("Você: ")
            if user_input.lower() == "sair":
                # Permite que um agente (ex: emocional ou mentor) gere uma despedida
                farewell_agent = self.agents.get("AgenteMentor") # Usando o Mentor para a despedida
                if farewell_agent:
                    farewell_response = farewell_agent.process_input("Usuário deseja encerrar a conversa.", self.conversation_history, self.user_profile)
                    self._log_conversation("bot", farewell_response)
                    print(f"BemEstarBot: {farewell_response}")
                else:
                     # Fallback caso o Agente Mentor não esteja disponível
                    fallback_farewell_agent = self.agents.get("AgenteSuporteEmocional")
                    if fallback_farewell_agent:
                         farewell_response = fallback_farewell_agent.process_input("Usuário deseja encerrar a conversa.", self.conversation_history, self.user_profile)
                         self._log_conversation("bot", farewell_response)
                         print(f"BemEstarBot: {farewell_response}")
                    else:
                         print("BemEstarBot: Tchau! Cuide-se!")
                break

            # O orquestrador processa a entrada do usuário (roteia e obtém a resposta do agente)
            response: str = self.process_user_input(user_input)

            print(f"BemEstarBot: {response}")

            # Em uma aplicação real, o orquestrador gerenciaria a persistência
            # do histórico da conversa e do perfil do usuário após cada interação.


def main() -> None:
    """
    Função principal para configurar as ferramentas, agentes e iniciar o orquestrador.
    """
    # Verifica se a ferramenta Gemini foi inicializada com sucesso globalmente
    if gemini_tool is None:
         print("\nSistema de Agentes não iniciado. A ferramenta Gemini não foi configurada corretamente.")
         print("Por favor, verifique sua chave de API e a lista de modelos disponíveis para sua conta.") # Mensagem aprimorada
         return

    # Inicializa os agentes, passando as ferramentas necessárias para cada um
    agents: Dict[str, BaseAgent] = {
        "AgenteSuporteEmocional": EmotionalSupportAgent(gemini_tool=gemini_tool),
        "AgenteExercicio": ExerciseAgent(gemini_tool=gemini_tool),
        "AgenteConhecimento": KnowledgeAgent(gemini_tool=gemini_tool),
        "AgenteMentor": MentorAgent(gemini_tool=gemini_tool), # Novo Agente Mentor adicionado
        # Adicionar outros agentes aqui no futuro
    }

    # Inicializa o Orquestrador com os agentes criados
    orchestrator = Orchestrator(agents=agents)

    # Inicia o loop de execução do orquestrador
    orchestrator.run()


if __name__ == "__main__":
    main()
